apiVersion: v1
kind: Pod
metadata:
  name: helm-pod
spec:
  containers:
  - name: helm
    image: acrarolibotnonprod.azurecr.io/helm-diff:v2.2.4
    command: ["sleep", "infinity" ]
    resources:
        requests:
          memory: 1Gi
          cpu: 800m
        limits:
          memory: 1Gi
          cpu: 800m
  - name: jnlp
    resources:
       requests:
         memory: 512Mi
         cpu: 800m
       limits:
         memory: 512Mi
         cpu: 800m 
  imagePullSecrets:
  - name: acr-registry
  serviceAccountName: infra-jenkins-agent
