apiVersion: v1
kind: Pod
metadata:
  name: helm-pod
spec:
  containers:
  - name: helm
    image: acrarolibotnonprod.azurecr.io/python-3.10-slim:v1.0.0
    command:
      - "sh"
      - "-c"
      - |
        apt update && apt install -y python3 python3-pip
        python3 -m pip install --upgrade pip
    resources:
        requests:
          memory: 1Gi
          cpu: 800m
        limits:
          memory: 1Gi
          cpu: 800m
  - name: jnlp
    resources:
       requests:
         memory: 512Mi
         cpu: 800m
       limits:
         memory: 512Mi
         cpu: 800m 
  imagePullSecrets:
  - name: acr-registry
  serviceAccountName: infra-jenkins-agent
